locale                   : "en-US"
title                    : "Ehsan Noei"
title_separator          : "-"
name                     : "Ehsan Noei"
description              : "Ehsan Noei Homepage"
url                      : "https://enoei.github.io"

#theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console
style: hacker # dark (default), light or hacker

header_pages:
  - index.md
  - docs.md
  - publications.md

markdown: kramdown

