# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site Settings
locale                   : "en-US"
title                    : "Ehsan Noei"
title_separator          : "-"
name                     : "Ehsan Noei"
description              : "Ehsan Noei Homepage"
url                      : "https://enoei.github.io"

# Build settings
#theme: minima
theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console
style: hacker # dark (default), light or hacker

header_pages:
  - index.md
  - docs.md
  - publications.md

#markdown: kramdown

